name: Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Build bootstrap
      run: |
        bash build_bootstrap.sh
    - name: Prepare Keystore 
      run: |   
         echo "${{ secrets.SIGNING_KEY }}" > tel.jks.asc   
         gpg -d --passphrase "${{ secrets.KEY_STORE_PASSWORD }}" --batch tel.jks.asc > app/tel.jks   
         echo "${{ secrets.KEYSTORE_PROPERTIES }}" > keystore.properties.asc   
         gpg -d --passphrase "${{ secrets.KEY_PASSWORD }}" --batch keystore.properties.asc > keystore.properties   
         echo "${{ secrets.AGCONNECT_SERVICES }}" > agconnect-services.json.asc    
         gpg -d --passphrase "${{ secrets.AGCONNECT_SERVICES_PASSPHRASE }}" --batch agconnect-services.json.asc > app/agconnect-services.json   
    - name: Build
      run: |
        ./gradlew :app:assembleRelease
    - name: Publish APK   
      uses: actions/upload-artifact@v2   
      with:   
        name: app-release   
        path: app/build/outputs/apk/release/
