name: Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Build bootstrap
      run: |
        bash build_bootstrap.sh
    - name: Prepare Keystore 
      run: |   
       echo "${{ secrets.KEYSTORE }}" > tel.jks.asc   
       gpg -d --passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --batch tel.jks.asc > app/tel.jks   
       echo "${{ secrets.KEYSTORE_PROPERTIES }}" > keystore.properties.asc   
       gpg -d --passphrase "${{ secrets.KEYSTORE_PROPERTIES_PASSPHRASE }}" --batch keystore.properties.asc > keystore.properties   
     
    - name: Build
      run: |
        ./gradlew :app:assembleRelease
    - name: Publish APK   
      uses: actions/upload-artifact@v2   
      with:   
        name: app-release   
        path: app/build/outputs/apk/release/
