name: Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Build bootstrap
      run: |
        bash build_bootstrap.sh
    - name: Prepare Keystore 
      run: |   
       echo "${{ secrets.KEYSTORE }}" > tel.jks.asc   
       echo "${{ secrets.KEYSTORE_PASS }}" | gpg -d --passphrase-fd 0 --batch tel.jks.asc > app/tel.jks   
       echo "${{ secrets.KEYSTORE_PROP }}" > keystore.properties.asc   
       gpg -d --passphrase "${{ secrets.KEYSTORE_PROP_PASS }}" --batch keystore.properties.asc > app/keystore.properties   
     
    - name: Build
      run: |
        ./gradlew :app:assembleRelease
    - name: Publish APK   
      uses: actions/upload-artifact@v2   
      with:   
        name: app-release   
        path: app/build/outputs/apk/release/
    - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "[BETA] TEL-${{ GITHUB_RUN_ID }}"
          files: |
            app/build/outputs/apk/release/*.apk
